Repository matteoredz/itax-code, pull requests merged in 2023-08, with the labels that each got.

#16 Improve omocodes algo
  .rubocop.yml
  Gemfile
  Rakefile
  bin/console
  itax_code.gemspec
  lib/itax_code.rb
  lib/itax_code/encoder.rb
  lib/itax_code/omocode.rb
  lib/itax_code/parser.rb
  lib/itax_code/utils.rb
  lib/itax_code/validator.rb
  lib/itax_code/version.rb
  rakelib/cities.rake
  test/itax_code/encoder_test.rb
  test/itax_code/parser_test.rb
  test/itax_code/validator_test.rb
  test/itax_code_test.rb
  test/test_helper.rb
Labels: enhancement

#17 fix: explicit the workflow permissions
  .github/workflows/release.yml
Labels: bug

#19 chore: update checkout action to v3
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: enhancement

#20 fix: disable MFA as it breaks the CI
  .rubocop.yml
  itax_code.gemspec
Labels: bug

#22 fix: compute omocodes from the original one
  lib/itax_code/omocode.rb
Labels: bug

#24 docs: update README.md
  README.md
Labels: enhancement

#25 fix!: raise InvalidControlInternalNumberError on cin mismatch
  .rubocop.yml
  lib/itax_code.rb
  lib/itax_code/encoder.rb
  lib/itax_code/parser.rb
  lib/itax_code/utils.rb
  lib/itax_code/validator.rb
  test/itax_code/parser_test.rb
  test/test_helper.rb
Labels: bug, enhancement

#26 feat!: allow empty or partial data argument in ItaxCode.valid?
  lib/itax_code.rb
  lib/itax_code/parser.rb
  lib/itax_code/validator.rb
  test/itax_code/validator_test.rb
Labels: enhancement

#27 fix: NoMethodError
  lib/itax_code/parser.rb
Labels: bug
